language: java
jdk:
  - oraclejdk8

install: ant

script:
  - ant integracion-continua
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 51818d08-af25-4c81-b546-3b87e37d6502

notifications:
  email:
    recipients:
      - tallo@fi.uba.ar

on_failure: always
